### ISSUE TITLE
Groupchats

### ISSUE THREAD

**Issue by xsploit** [KevinAdhaikal/CAINode#6]
I' habing issues with groupchats are you able to show how you use it?

**Comment by KevinAdhaikal** [comment]
to use Group Chat, you must get the Group Chat ID by calling (group_chat.list())[https://github.com/kevinAdhaikal/cainode?tab=readme-ov-file#group_chatlist] function.

```
...
await console.log(client.group_chat.list());
...
```

after you get the group chat id, and then connect by calling (group_chat.list())[https://github.com/kevinAdhaikal/cainode?tab=readme-ov-file#group_chatconnect] function.

```
...
await console.log(client.group_chat.connect("Group Chat ID"));
...
```

**Comment by KevinAdhaikal** [comment]
is it solved?

**Comment by xsploit** [comment]
I got it work thx. Then i relaized it doesnt work with tts. I actually made my.own project with the api thx

**Comment by KevinAdhaikal** [comment]
no problem 👍

**Comment by KevinAdhaikal** [comment]
> I got it work thx. Then i relaized it doesnt work with tts. I actually made my.own project with the api thx

oh about the tts, it already fix it, but i haven't published it to npm yet

**Comment by KevinAdhaikal** [comment]
https://github.com/KevinAdhaikal/CAINode/pull/5

**Comment by xsploit** [comment]
yea i know i pasted the new index.js
________________________________
