### ISSUE TITLE
Multi user management

### ISSUE THREAD

**Issue by PikaBotz** [KevinAdhaikal/CAINode#7]
Bro suppose if me and my friend wanna use the same character and access token but wanna chat with the character separately. Then how it's possible? I mean we both wanna chat separately and don't wanna mix our conversations. I'm really confused.

**Comment by KevinAdhaikal** [comment]
oh, so you need to set the chat id manually. i will make the tutorial later on the README.md, okay?

**Comment by PikaBotz** [comment]
Thanks alot! Actually I want the ai to remember whom she's/he's talking to.
Basically I'll set it in https://github.com/PikaBotz/Anya_v2-MD (and I'll
use whatsapp Baileys JID for chat id like: ***@***.***)

**Comment by KevinAdhaikal** [comment]
I've just updated the CAINode version to v1.1.8.
you can do Multi user.

**Comment by KevinAdhaikal** [comment]
Example

```js
const new_chat_id = await client.character.create_new_conversation(false, {
    char_id: "Your Character ID"
})
await client.character.send_message("hello world", false, "", {
    chat_id: new_chat_id.chat.chat_id,
    char_id: "Your Character ID"
})
```

**Comment by KevinAdhaikal** [comment]
now, you can send a message with a specific chat id.

**Comment by KevinAdhaikal** [comment]
Sorry if I make you wait for 1 month 😂

**Comment by PikaBotz** [comment]
> Sorry if I make you wait for 1 month 😂

That's more than I asked for 🌟

But... It's creating new convo each time of execution and i want to use seprate chats per input ID

**Comment by PikaBotz** [comment]
Okay let's be on point, I want the AI to remember who she's/he's talking to.

**Comment by KevinAdhaikal** [comment]
> Okay let's be on point, I want the AI to remember who she's/he's talking to.

ohhh... you mean, using one chat id? right?

**Comment by PikaBotz** [comment]
> > Okay let's be on point, I want the AI to remember who she's/he's talking to.


> ohhh... you mean, using one chat id? right?


Yes yes! Exactly. I'm seriously confused about how to handle different chat IDs. Your function showcase is really clear and simple, but how, where, and why to use this or that function isn’t fully clear.

And look at here,
![IMG_20241128_160050](https://github.com/user-attachments/assets/99733c09-d11e-40e3-9251-5cab4fc56170)

Regarding RAM usage: It's a really decent and impressive number—great job on that!
However, response time is a concern. 8–12 seconds (without voice support) and 8–15+ seconds with voice support is not acceptable for smooth interactions.

```javascript
const TOKEN = "1234abcXXXX";
const CID = "5678efghYYYY";

(async function() {
    const { CAINode } = await import("cainode");
    const client = new CAINode();

    try {
        await client.login(TOKEN);
        console.log("Logged in successfully!");

        await client.character.connect(CID);
        console.log("Connected to character.");

        await client.character.send_message("Hi", true);
        console.log("Message sent.");

        const output = await client.character.generate_turn();
        console.log("Response:", output);

    } catch (error) {
        console.error("An error occurred:", error);
    } finally {
        await client.logout();
        console.log("Logged out.");
    }
})();
```

**Comment by KevinAdhaikal** [comment]
you can do it like this

```
const TOKEN = "1234abcXXXX";
const CID = "5678efghYYYY";

(async function() {
    const { CAINode } = await import("cainode");
    const client = new CAINode();
    try {
        await client.login(TOKEN);
        console.log("Logged in successfully!");

        const chat_id_1 = "Input Chat ID here";
        const chat_id_2 = "Input another Chat ID here";

        // for chat ID 1
        await client.character.send_message("Hi", true, undefined, {
            chat_id: chat_id_1,
            char_id: CID
        });
        console.log("[Chat ID 1] Message sent.");

        let output = await client.character.generate_turn({
            chat_id: chat_id_1,
            char_id: CID
        });
        console.log("[Chat ID 1] Response:", output);

        // for chat ID 2
        await client.character.send_message("Hi", true, undefined, {
            chat_id: chat_id_2,
            char_id: CID
        });
        console.log("[Chat ID 2] Message sent.");

        output = await client.character.generate_turn({
            chat_id: chat_id_2,
            char_id: CID
        });
        console.log("[Chat ID 2] Response:", output);

    } catch (error) {
        console.error("An error occurred:", error);
    } finally {
        await client.logout();
        console.log("Logged out.");
    }
})();
```

**Comment by PikaBotz** [comment]
> you can do it like this
> 
> ```js
> const TOKEN = "1234abcXXXX";
> const CID = "5678efghYYYY";
> 
> (async function() {
>     const { CAINode } = await import("cainode");
>     const client = new CAINode();
>     try {
>         await client.login(TOKEN);
>         console.log("Logged in successfully!");
> 
>         const chat_id_1 = "Input Chat ID here";
>         const chat_id_2 = "Input another Chat ID here";
> 
>         // for chat ID 1
>         await client.character.send_message("Hi", true, undefined, {
>             chat_id: chat_id_1,
>             char_id: CID
>         });
>         console.log("[Chat ID 1] Message sent.");
> 
>         let output = await client.character.generate_turn({
>             chat_id: chat_id_1,
>             char_id: CID
>         });
>         console.log("[Chat ID 1] Response:", output);
> 
>         // for chat ID 2
>         await client.character.send_message("Hi", true, undefined, {
>             chat_id: chat_id_2,
>             char_id: CID
>         });
>         console.log("[Chat ID 2] Message sent.");
> 
>         output = await client.character.generate_turn({
>             chat_id: chat_id_2,
>             char_id: CID
>         });
>         console.log("[Chat ID 2] Response:", output);
> 
>     } catch (error) {
>         console.error("An error occurred:", error);
>     } finally {
>         await client.logout();
>         console.log("Logged out.");
>     }
> })();
> ```

Thanks again!🌟
I'll test it soon, and i know you'll do something about the response time soon.

**Comment by KevinAdhaikal** [comment]
no problem 👍

**Comment by KevinAdhaikal** [comment]
to get list of the chat id, you can call this function
`await client.chat.history_conversation_list(character_id)`

**Comment by PikaBotz** [comment]
> to get list of the chat id, you can call this function `await client.chat.history_conversation_list(character_id)`

No worries, actually I'll assign chat id for each and different userIDs using mongodb 

Like:
```javascript
{
   "123@abc": "xyz_chatID",
   "456@efgh": "xyz_chatID2",
...and more...
}
```

**Comment by KevinAdhaikal** [comment]
oh, nice.

**Comment by PikaBotz** [comment]
> oh, nice.

Ah bro bro bro! Listen 
[`Dippy AI`](https://www.dippy.ai/)

What about this AI?

**Comment by KevinAdhaikal** [comment]
> > oh, nice.
> 
> Ah bro bro bro! Listen [`Dippy AI`](https://www.dippy.ai/)
> 
> What about this AI?

what do you mean?

**Comment by PikaBotz** [comment]
> > > oh, nice.
> > 
> > 
> > Ah bro bro bro! Listen [`Dippy AI`](https://www.dippy.ai/)
> > What about this AI?
> 
> what do you mean?

I mean you made a really awesome npm package for [`character.ai`](character.ai) so do you have any plans for [`dippy.ai`](dippy.ai) npm package? To intract with dippy.ai bots?

**Comment by KevinAdhaikal** [comment]
> > > > oh, nice.
> > > 
> > > 
> > > Ah bro bro bro! Listen [`Dippy AI`](https://www.dippy.ai/)
> > > What about this AI?
> > 
> > 
> > what do you mean?
> 
> I mean you made a really awesome npm package for [`character.ai`](character.ai) so do you have any plans for [`dippy.ai`](dippy.ai) npm package? To intract with dippy.ai bots?

hmmm... idk, im lazy to do it

btw.. is this issue solved?

**Comment by KevinAdhaikal** [comment]
i will close the issue as solved.

if its still not solved, please reopen the issue. okay?

**Comment by PikaBotz** [comment]
Okay I tested your given code and it's working good. So I have a question, any issue if I leave the convention to character open, and don't close it

**Comment by PikaBotz** [comment]
> i will close the issue as solved.
> 
> if its still not solved, please reopen the issue. okay?

Okay I tested your given code and it's working good. So I have a question, any issue if I leave the convention to character open, and don't close it

**Comment by KevinAdhaikal** [comment]
> Okay I tested your given code and it's working good. So I have a question, any issue if I leave the convention to character open, and don't close it

Hmmmmm... i hope there's no issues, hehe. 😁 
But if you get any issues in my CAINode, don't hesitate to create an issue and report to me, okay?

**Comment by PikaBotz** [comment]
> > Okay I tested your given code and it's working good. So I have a question, any issue if I leave the convention to character open, and don't close it
> 
> Hmmmmm... i hope there's no issues, hehe. 😁 But if you get any issues in my CAINode, don't hesitate to create an issue and report to me, okay?

Yep a lil issue for now, with the images. Cai can't see the images?

**Comment by PikaBotz** [comment]
# API endpoint response:
![IMG_20241216_134627](https://github.com/user-attachments/assets/05bf4b7c-71f1-49ba-911b-7a13d76c671b)

# the image url i inserted:
s![Image](https://i.ibb.co/JkPBJvj/images.jpg)

**Comment by KevinAdhaikal** [comment]
> > > Okay I tested your given code and it's working good. So I have a question, any issue if I leave the convention to character open, and don't close it
> > 
> > 
> > Hmmmmm... i hope there's no issues, hehe. 😁 But if you get any issues in my CAINode, don't hesitate to create an issue and report to me, okay?
> 
> Yep a lil issue for now, with the images. Cai can't see the images?

yeah... Character AI cannot see the picture. I don't know why.
