### ISSUE TITLE
chat.pin_message() won't unpin messages.

### ISSUE THREAD

**Issue by wang-yuwen** [KevinAdhaikal/CAINode#9]
So pinning messages works fine, but putting the 'false' value doesn't seem to unpin messages. I've tried sending some other requests but couldn't find a separate 'command' to unpin a turn. Putting "set_turn_pin" seems to always pin the message even if "is_pinned" is set to false.

**Comment by KevinAdhaikal** [comment]
did you try make the second parameter to false? like `await client.chat.pin_message("turn ID", false, "Chat ID")`

**Comment by wang-yuwen** [comment]
Yeah, I double checked everything before posting this. Can't find a solution, so I thought I'd let you know.

**Comment by KevinAdhaikal** [comment]
ohhh... i'll try it, thanks for reporting the bug!

**Comment by KevinAdhaikal** [comment]
hmmmmm... mine is work as well... no issue

**Comment by KevinAdhaikal** [comment]
maybe you put it wrong

**Comment by KevinAdhaikal** [comment]
and remember, the first parameter it should be "turn_id". not "candidate_id".

**Comment by wang-yuwen** [comment]
Oh. Right, so it turned out I forgot to add an 'await' to my function that returns the turn id🤦‍♂️.  That's why I couldn't use it. 
Everything's fine now, you can close the issue.

**Comment by KevinAdhaikal** [comment]
Okay 👍
